name: guard-find-backend
services:
  guard-find-backend-mysql:
    image: mysql:8.0.42
    container_name: guard-find-backend-mysql
    restart: always
    ports:
      - '23306:3306'
    volumes:
      - /docker/guard-find-backend/mysql/conf/:/etc/mysql/conf.d/
      - /docker/guard-find-backend/mysql/data/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 你的root用户密码
      MYSQL_DATABASE: guard_find_backend
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
  guard-find-backend-redis:
    image: redis:7.2.8
    container_name: guard-find-backend-redis
    restart: always
    ports:
      - '26379:6379'
    volumes:
      - /docker/guard-find-backend/redis/conf/redis.conf:/usr/local/redis/config/redis.conf
      - /docker/guard-find-backend/redis/data/:/data/
      - /docker/guard-find-backend/redis/logs/:/logs/
    environment:
      TZ: Asia/Shanghai
    command: 'redis-server /usr/local/redis/config/redis.conf --appendonly yes'
  guard-find-backend-api:
    build: ./guard-find-backend-api
    image: guard-find-backend-api:4.2.0-SNAPSHOT
    container_name: guard-find-backend-api
    restart: always
    ports:
      - '28000:18000'
      - '27889:17889'
    volumes:
      - /docker/guard-find-backend/api/config/:/app/config/
      - /docker/guard-find-backend/api/data/file/:/app/data/file/
      - /docker/guard-find-backend/api/logs/:/app/logs/
      - /docker/guard-find-backend/api/lib/:/app/lib/
    environment:
      TZ: Asia/Shanghai
      PROFILES_ACTIVE: prod
      DB_HOST: guard-find-backend-mysql
      DB_PORT: 3306
      DB_USER: 你的数据库用户名
      DB_PWD: 你的数据库密码
      DB_NAME: guard_find_backend
      REDIS_HOST: guard-find-backend-redis
      REDIS_PORT: 6379
      REDIS_PWD: 你的 Redis 密码
      REDIS_DB: 0
      SCHEDULE_HOST: guard-find-backend-schedule
      SCHEDULE_PORT: 1788
      SCHEDULE_TOKEN: 任务调度服务端 Token
    depends_on:
      - guard-find-backend-mysql
      - guard-find-backend-redis
  guard-find-backend-schedule:
    build: ./guard-find-backend-schedule
    image: guard-find-backend-schedule:1.8.0
    container_name: guard-find-backend-schedule
    restart: always
    ports:
      - '28001:18001'
      - '27888:17888'
    volumes:
      - /docker/guard-find-backend/schedule/logs/:/app/logs/
    environment:
      TZ: Asia/Shanghai
      DB_HOST: guard-find-backend-mysql
      DB_PORT: 3306
      DB_USER: 你的数据库用户名
      DB_PWD: 你的数据库密码
      DB_NAME: guard_find_backend_job
    depends_on:
      - guard-find-backend-mysql
